version: "3.9"
services:
  storage:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
    ports:
      - 5432:5432
